packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@whiskeysockets/baileys": true
  argon2: true
  esbuild: true
  protobufjs: true

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  "@esbuild-kit/core-utils@3.3.2>esbuild": "0.25.12"
  "esbuild@>=0.27.3 <0.28.1": "0.28.1"
